index:
    path: /
    controller: App\Controller\DefaultController::index

userAuth:
    path: /api/authenticate
    controller: App\Controller\Api\UserController::authenticate
    methods: [OPTIONS, POST]

userCreate:
    path: /api/user/register
    controller: App\Controller\Api\UserController::create
    methods: [OPTIONS, POST]

userRead:
    path: /api/user
    controller: App\Controller\Api\UserController::read
    methods: [OPTIONS, POST, GET]
userUpdate:
    path: /api/user/{id}
    controller: App\Controller\Api\UserController::update
    methods: [PUT]